version: "3.8"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sales_points
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: app_db

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL= jdbc:postgresql://app_db:5432/sales_points
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=12345


volumes:
  postgres-data:
